# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZYSgQ3NYQtRW3uXo2lVFRAMNv1642U5w
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import gradio as gr

# Step 2: Load Dataset
url = "https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv"
data = pd.read_csv(url)

# Display first few rows
print("Dataset Preview:")
display(data.head())

# Step 3: Basic Info
print("\nDataset Shape:", data.shape)
print("\nMissing Values:\n", data.isnull().sum())

# Step 4: Data Visualization
plt.figure(figsize=(10,6))
sns.heatmap(data.corr(), annot=True, cmap='coolwarm')
plt.title("Feature Correlation Heatmap")
plt.show()

# Step 5: Split Data
X = data.drop('Outcome', axis=1)
y = data['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 6: Scale Features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 7: Train Model
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Step 8: Evaluate Model
y_pred = model.predict(X_test_scaled)
print("\n✅ Model Accuracy:", round(accuracy_score(y_test, y_pred)*100, 2), "%")

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Step 9: Build Gradio App
def predict_diabetes(Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age):
    # Create dataframe from input
    input_data = pd.DataFrame([[Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age]],
                              columns=['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age'])
    input_scaled = scaler.transform(input_data)
    prediction = model.predict(input_scaled)[0]
    probability = model.predict_proba(input_scaled)[0][1]

    if prediction == 1:
        return f"⚠️ The person is likely to have diabetes. (Confidence: {probability*100:.2f}%)"
    else:
        return f"✅ The person is unlikely to have diabetes. (Confidence: {(1-probability)*100:.2f}%)"

# Step 10: Launch Gradio Interface
inputs = [
    gr.Slider(0, 20, step=1, label="Pregnancies"),
    gr.Slider(0, 200, step=1, label="Glucose Level"),
    gr.Slider(0, 140, step=1, label="Blood Pressure"),
    gr.Slider(0, 100, step=1, label="Skin Thickness"),
    gr.Slider(0, 900, step=1, label="Insulin"),
    gr.Slider(10, 70, step=0.1, label="BMI"),
    gr.Slider(0.0, 2.5, step=0.01, label="Diabetes Pedigree Function"),
    gr.Slider(10, 100, step=1, label="Age")
]

gr.Interface(
    fn=predict_diabetes,
    inputs=inputs,
    outputs=gr.Textbox(label="Prediction"),
    title="🩺 Diabetes Risk Predictor",
    description="Enter the health details below to check if a person is likely to have diabetes.",
    theme="default"
).launch()